### ISSUE TITLE
`-mergeoutput` option usage

### ISSUE THREAD

**Issue by eduherminio** [danielpalme/ReportGenerator-GitHub-Action#12]
How can `-mergeoutput` option be passed, in order to append the results to an existing report?
How is the existing report provided?

Use case: tests divided in two GH action jobs running sequentially: the idea is to download the existing report from the artifacts list, update it and re-upload it.

Current setup (in the first job):

```yaml
    - name: 'Generate test coverage report'
      uses: danielpalme/ReportGenerator-GitHub-Action@4.8.11
      with:
        reports: 'tests/**/*.cobertura.xml'
        targetdir: 'coveragereport'
        reporttypes: 'HtmlInline_AzurePipelines_Dark;SonarQube'
        assemblyfilters: '+*'
        classfilters: '+*;-*Exception;'
        filefilters: '+*'
        verbosity: 'Info'
        title: 'MyProject - #${{ github.run_number }})'
        tag: '${{ github.run_number }}_${{ github.run_id }}'
        customSettings: 'numberOfReportsParsedInParallel=3;numberOfReportsMergedInParallel=3'

    - name: 'Upload test coverage report'
      uses: actions/upload-artifact@v2
      with:
        name: MyProject-coverage-ci-${{ github.run_number }}
        path: coveragereport/
        if-no-files-found: error
```
