### ISSUE TITLE
Readme: add example of posting code cov PR comment

### ISSUE THREAD

**Issue by alexandrehtrb** [danielpalme/ReportGenerator-GitHub-Action#19]
Hello,

It would be nice to add an example of how to post the code cov summary in a PR comment:

Example:

```yml
- name: Add comment to PR
  if: github.event_name == 'pull_request'
  run: gh pr comment $PR_NUMBER --body-file ./TestResults/Summary.md
  env:
    GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    PR_NUMBER: ${{ github.event.number }}
```
