### ISSUE TITLE
Update documentation for attaching Markdown summaries to GitHub PRs

### ISSUE THREAD

**Issue by MTroesterSoftfair** [danielpalme/ReportGenerator-GitHub-Action#24]
Hi Daniel,

your tool is great, I'm loving it.

Your README inspired me to attach a GitHub Markdown report format to my PRs. The problem is, it doesn't work as your README says.

The GH CLI tool kept asking which branch it's on. I couldn't seem to get that to work. So I ended up using ``actions/github-script@v7`` and ``github.rest.issues.createComment`` instead. But even for that approach, the PR comment body has a size limit of 65k which your Markdown report overran, so I had to truncate the content.

My final version looked something like this:

```yml
- name: Attach test coverage report to PR
  uses: actions/github-script@v7
  with:
    script: |
      const fs = require('fs')
      var fileContents = fs.readFileSync('./reports/test_coverage/SummaryGithub.md').toString()

      if (fileContents.length > 60000) {
        const contentLines = fileContents.split(/\r?\n/)
        const filteredLines = contentLines.filter(item => !item.startsWith("xxxxx"))
        fileContents = filteredLines.join("\n")
      }

      github.rest.issues.createComment({
        issue_number: context.issue.number,
        owner: context.repo.owner,
        repo: context.repo.repo,
        body: fileContents
      })
```

Maybe you can update your README using my stuff and implement a truncation to avoid the size limit. But anyways, do whatever you want with my stuff. Just putting it out there for others who run into this issue.

Thanks again for providing this great tool.

Best wishes,
Marco

**Comment by MTroesterSoftfair** [comment]
Btw, another approach would be uploading the report as an artifact and commenting the download link into the PR via chatbot.

```yml
jobs:
  runs-on: windows-latest
  permissions:
      pull-requests: write
  steps:
      - name: Generate test coverage report
        uses: danielpalme/ReportGenerator-GitHub-Action@5.4.4
        with:
          reports: TestResults/*/coverage.cobertura.xml
          targetdir: reports/test_coverage
          reporttypes: Html,MarkdownSummaryGithub
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        id: coverage-upload
        with:
          name: test_coverage
          path: ./reports/test_coverage
      - name: Attach detailed test coverage link to PR
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Download detailed coverage report here: " + "${{ steps.coverage-upload.outputs.artifact-url }}"
            })
```
