### ISSUE TITLE
Question: is it possible to show coverage report on Pull Request page

### ISSUE THREAD

**Issue by antonshell** [danielpalme/ReportGenerator-GitHub-Action#7]
Hello,

I'm tryed to use this github action. Added it to my tests workflow.
It works fine, but I don't understand how to see the report.

![image](https://user-images.githubusercontent.com/5452932/107738324-7a644880-6d17-11eb-8606-23b8cc31fcd1.png)

In general, I would like to see in Pull Request page.
There is another action: https://github.com/marketplace/actions/clover-code-coverage-report
And there is a posting the comment with report. Is it possible to do something like that?

![image](https://user-images.githubusercontent.com/5452932/107738450-bdbeb700-6d17-11eb-94f6-792b30be29c1.png)

**Comment by danielpalme** [comment]
You can publish the report as an artifact:

```yaml
    - name: Upload coverage report artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: CoverageReport # Artifact name        
        path: coverage # Directory containing files to upload
```

**Comment by antonshell** [comment]
Ok, thank you! Will try

**Comment by revenue-nikhil-sharma** [comment]
Hi @danielpalme , on uploading the artifacts, the coverage is still not showing on the pull request. 
Though on downloading-extracting the artifiacts, it shows me all the relevant files. 
Am I missing something?

**Comment by danielpalme** [comment]
My extension "just" generates the report. It does not add any information to your PRs.

**Comment by danielpalme** [comment]
You may want to give this extension a try: https://github.com/marketplace/actions/sticky-pull-request-comment

The workflow would look similar to this:
```yaml
- name: ReportGenerator
  uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
  with:
    reports: 'coverage.xml'
    targetdir: 'coveragereport'
    reporttypes: 'HtmlInline;Cobertura;MarkdownSummary' 

- name: Publish coverage summary
  uses: marocchino/sticky-pull-request-comment@v2
  with:
    path: coveragereport/Summary.md
```

See also: https://github.com/danielpalme/ReportGenerator/issues/431
